### ISSUE TITLE
Bell doesn't ring

### ISSUE THREAD

**Issue by MasterCarl** [hpibandraum/ring#1]
When triggering the bell, I get "Error - plug it in" and it doesn't ring. It seems like a connectivity issue. The status LED of the bell blinks blue.

**Comment by niccokunzmann** [comment]
Here you can see the status codes. Which one is it?
https://docs.particle.io/guide/getting-started/modes/photon/#photon-modes-listening-mode

**Comment by niccokunzmann** [comment]
I added the error status as output. It says "timed out" for me - maybe there is a bad wifi connection. I can not go into the room to check this out.

**Comment by MasterCarl** [comment]
Seems to work now
